tensorflow benchmark
Signed-off-by: Ericyuanhui <yuanhui.xu@intel.com>

diff --git a/Tools/development/tensorflow/dl_framework-intel_tensorflow_models/tools/build_tf b/Tools/development/tensorflow/dl_framework-intel_tensorflow_models/tools/build_tf
--- a/Tools/development/tensorflow/dl_framework-intel_tensorflow_models/tools/build_tf
+++ b/Tools/development/tensorflow/dl_framework-intel_tensorflow_models/tools/build_tf
@@ -18,7 +18,10 @@ while getopts ":ht:" opt; do
                 eigen ) version_to_build=0 ;;
                 mkl ) version_to_build=1 ;;
                 mkldnn ) version_to_build=2 ;;
-                : ) echo "Invalid version: eigen, mkl, mkldnn" ;;
+                : )
+                    echo "Invalid version: eigen, mkl, mkldnn"
+                    exit 1
+                ;;
             esac
             ;;
         \? ) echo "Usage: build_tf [-t] VERSION (eigen, mkl, mkldnn), eigen by default" ;;
@@ -39,7 +42,14 @@ then
     echo "MKLDNN will be built..."
     bazel build --copt -O3 --copt=-DINTEL_MKL_DNN --config=mkl -c opt //tensorflow/tools/pip_package:build_pip_package
 else
-    echo "Internal ERROR: $version_to_build"
+    echo "Internal ERROR: $version_to_build. This should NOT happen at all!"
+    exit 1
+fi
+
+# Check the error code
+if [ $? -ne 0 ]
+then
+    exit $?
 fi
 
 # Generate the .whl file
